name: styled_widget
description: Simplifying widget style with the use of dart extentions
version: 0.0.1
author: Rein Gundersen Bentdal
homepage: https://github.com/ReinBentdal/styled_widget

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
