name: styled_widget
description: Simplifying your widget tree structure by using a method based widget tree structure, inspired by SwiftUI.
version: 0.0.1+2
homepage: https://github.com/ReinBentdal/styled_widget
repository: https://github.com/ReinBentdal/styled_widget

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^1.12.13

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
