name: styled_widget
description: Style your widget using methods
version: 0.0.1
author: Rein Gundersen Bentdal
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
